name: WeatherNotify

on:
  schedule:
    # UTC Time 기준으로 아래 시간에 +9를 해야 함
    - cron: 05 22 * * SUN-THU
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run python file
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CHANNEL_NAME }}
        run: |
          python weatherbot.py "$SLACK_WEBHOOK_URL" "$SLACK_CHANNEL_NAME"
